name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
      - run: | 
          PORT=$(cut -d ' ' -f 4 <<< ${{ secrets.SSH_TERMINAL_CMD }})
          expect -c "
          set timeout 3
          spawn ssh -t -L 10020:35.190.225.93:${PORT} money-book@stg1-jenkins01.ebisubook.com \"${{ secrets.SSH_TERMINAL_CMD}} \"
          expect \"Password:\"
          send \"stgebisu\n\"
          expect \"Password:\"
          send \"${{ secrets.SSH_PSW }}\n\"
          interact
          "
