name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: sudo apt install expect
      - run: bats -v
      - run: pwd
      - run: | 
          PORT=$(cut -d ' ' -f 4 <<< "${{ secrets.SSH_TERMINAL_CMD }}")
          expect -c "
          set timeout 3
          spawn ssh -t -L ${{ secrets.JENKINS_IP }}:${PORT} ${{ secrets.JENKINS_DOMAIN }} \"${{ secrets.SSH_TERMINAL_CMD}} \"
          expect \"Password:\"
          send \"{{ secrets.JENKINS_PWD }}\n\"
          expect \"Password:\"
          send \"${{ secrets.SSH_PSW }}\n\"
          interact
          "
      - run: pwd
