name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make jenkins ssh private key
        run: | 
          echo "${{ secrets.JENKINS_SECRET_KEY }}" > id_rsa_jenkins
      - name: Make kinsta ssh private key
        run: |
          echo "${{ secrets.KINSTA_SECRET_KEY }}" > id_rsa_kinsta
      - name: Make ssh config
        run: |
          chmod 600 id_rsa_jenkins
          chmod 600 id_rsa_kinsta
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh 
          touch /home/runner/.ssh/config
          echo "Host jenkins" >> /home/runner/.ssh/config
          echo "HostName ${{ secrets.JENKINS_HOST }}" >> /home/runner/.ssh/config
          echo "User ${{ secrets.JENKINS_USER }}" >> /home/runner/.ssh/config
          echo "IdentityFile id_rsa_jenkins" >> /home/runner/.ssh/config
          echo "LocalForward ${{ secrets.LOCAL_FORWARD_PORT }} ${{ secrets.LOCAL_FORWARD_IP }}:${{ secrets.PORT }}" >> /home/runner/.ssh/config
          echo "Host kinsta" >> /home/runner/.ssh/config
          echo "HostName ${{ secrets.KINSTA_HOST }}" >> /home/runner/.ssh/config
          echo "ServerAliveInterval 60" >> /home/runner/.ssh/config
          echo "ServerAliveCountMax 5" >> /home/runner/.ssh/config
          echo "StrictHostKeyChecking no" >> /home/runner/.ssh/config
          echo "UserKnownHostsFile /dev/null" >> /home/runner/.ssh/config
          echo "User ${{ secrets.KINSTA_USER }}" >> /home/runner/.ssh/config
          echo "Port ${{ secrets.PORT }}" >> /home/runner/.ssh/config
          echo "IdentityFile id_rsa_kinsta" >> /home/runner/.ssh/config
          echo "StrictHostKeyChecking no" >> /home/runner/.ssh/config
          echo "UserKnownHostsFile /dev/null" >> /home/runner/.ssh/config
          echo "ProxyJump jenkins" >> /home/runner/.ssh/config
          chmod 600 /home/runner/.ssh/*

      - name: Proxy ssh
        run: |
          ssh -vvv -T kinsta "pwd"

