name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install expect
      - run: pwd
      - name: Proxy ssh
        run: |
          echo "${{ secrets.SECRET_KEY }}" > secret_key
          echo "${{ secrets.ALL_SECRET_KEY }}" > all_secret_key 
          PORT=$(cut -d ' ' -f 4 <<< "${{ secrets.ESTBASIC_STAGING_SSH_TERMINAL_CMD }}")
          ssh -p ${PORT} -i all_secret_key -o ProxyCommand="ssh -L {{ $JENKINS_IP }}:${PORT} {{ JENKINS_DOMAIN }} -i secret_key -W %h:%p" fofojoku@35.190.225.93
