name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make jenkins ssh private key
        run: | 
          echo "${{ secrets.JENKINS_SECRET_KEY }}" > jenkins_secret_key
          chmod 600 jenkins_secret_key
      - name: Make kinsta ssh private key
        run: |
          echo "${{ secrets.KINSTA_SECRET_KEY }}" > kinsta_secret_key
          chmod 600 kinsta_secret_key
      - name: Make ssh config
        run: |
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/config
          echo "Host jenkins" >> /home/runner/.ssh/config
          echo "HostName ${{ secrets.JENKINS_HOST }}" >> /home/runner/.ssh/config
          echo "User ${{ secrets.JENKINS_USER }}" >> /home/runner/.ssh/config
          echo "IdentityFile jenkins_secret_key" >> /home/runner/.ssh/config
          echo "LocalForward ${{ secrets.LOCAL_FORWARD_PORT }} ${{ secrets.LOCAL_FORWARD_IP }}:${{ secrets.PORT }}" >> /home/runner/.ssh/config
          echo "Host kinsta" >> /home/runner/.ssh/config
          echo "HostName ${{ secrets.KINSTA_HOST }}" >> /home/runner/.ssh/config
          echo "User ${{ secrets.KINSTA_USER }}" >> /home/runner/.ssh/config
          echo "Port ${{ secrets.PORT }}" >> /home/runner/.ssh/config
          echo "IdentityFile kinsta_secret_key" >> /home/runner/.ssh/config
          echo "ProxyCommand ssh -CW %h:%p jenkins" >> /home/runner/.ssh/config

      - name: Proxy ssh
        run: |
          ssh -t -t kinsta
          pwd
          exit

