name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install expect
      - run: sudo apt-get install sshpass
      - run: pwd
      - run: |
          echo "${{ secrets.SECRET_KEY }}" > secret_key 
          PORT=$(cut -d ' ' -f 4 <<< "${{ secrets.ESTBASIC_STAGING_SSH_TERMINAL_CMD }}")
          sshpass -p ${{ secrets.ESTBASIC_STAGING_SSH_PSW }} ssh -t -ti secret_key -L ${{ secrets.JENKINS_IP }}:${PORT} ${{ secrets.JENKINS_DOMAIN }} \"${{ secrets.ESTBASIC_STAGING_SSH_TERMINAL_CMD }}\"
          pwd
      - run: pwd
